%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-rqt-gui-cpp
Version:        0.5.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rqt_gui_cpp package

License:        BSD
URL:            http://ros.org/wiki/rqt_gui_cpp
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-nodelet
Requires:       ros-noetic-qt-gui >= 0.3.0
Requires:       ros-noetic-qt-gui-cpp >= 0.3.0
Requires:       ros-noetic-roscpp
BuildRequires:  qt5-qtbase-devel
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-nodelet
BuildRequires:  ros-noetic-qt-gui >= 0.3.0
BuildRequires:  ros-noetic-qt-gui-cpp >= 0.3.0
BuildRequires:  ros-noetic-roscpp
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
rqt_gui_cpp enables GUI plugins to use the C++ client library for ROS.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Mar 10 2020 Dirk Thomas <dthomas@osrfoundation.org> - 0.5.1-1
- Autogenerated by Bloom

